### ISSUE TITLE
No matching distribution found for transferwise-python-sdk

### ISSUE THREAD

**Issue by MarioHBS** [davidvartanian/transferwise-python-sdk#2]
ERROR: Could not find a version that satisfies the requirement transferwise-python-sdk (from versions: none)
ERROR: No matching distribution found for transferwise-python-sdk

Windows 10

**Comment by micheledicosmo** [comment]
+1 on Ubuntu under WLS

**Comment by rsurikov** [comment]
+1

**Comment by davidvartanian** [comment]
Thanks everyone for reporting. I've just fixed the issue and also updated setup.py with the correct license code (v0.0.2).
